problem:
  L: 1.0
  T0: 0.0
  T1: 1.0
  N_f: 2000          # کاهش از ۵۰۰۰ به ۲۰۰۰

network:
  layers: [2, 50, 50, 50, 50, 3]

training:
  adam_lr: 1e-3
  adam_iters: 3000   # کاهش از ۵۰۰۰ به ۳۰۰۰
  use_lbfgs: true

inverse:
  enable: true
  lambda_data: 100.0 # افزایش از ۵۰ به ۱۰۰
  n_data_points: 500
  noise_level: 0.005
  use_uncertainty: true
  varying_params: true
